/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package accounts;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class transaction_closed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8641696874307477822L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"transaction_closed\",\"namespace\":\"accounts\",\"fields\":[{\"name\":\"attempt\",\"type\":\"int\"},{\"name\":\"transaction_url\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<transaction_closed> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<transaction_closed> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<transaction_closed> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<transaction_closed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<transaction_closed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this transaction_closed to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a transaction_closed from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a transaction_closed instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static transaction_closed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int attempt;
  private java.lang.String transaction_url;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public transaction_closed() {}

  /**
   * All-args constructor.
   * @param attempt The new value for attempt
   * @param transaction_url The new value for transaction_url
   */
  public transaction_closed(java.lang.Integer attempt, java.lang.String transaction_url) {
    this.attempt = attempt;
    this.transaction_url = transaction_url;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return attempt;
    case 1: return transaction_url;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: attempt = (java.lang.Integer)value$; break;
    case 1: transaction_url = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'attempt' field.
   * @return The value of the 'attempt' field.
   */
  public int getAttempt() {
    return attempt;
  }


  /**
   * Sets the value of the 'attempt' field.
   * @param value the value to set.
   */
  public void setAttempt(int value) {
    this.attempt = value;
  }

  /**
   * Gets the value of the 'transaction_url' field.
   * @return The value of the 'transaction_url' field.
   */
  public java.lang.String getTransactionUrl() {
    return transaction_url;
  }


  /**
   * Sets the value of the 'transaction_url' field.
   * @param value the value to set.
   */
  public void setTransactionUrl(java.lang.String value) {
    this.transaction_url = value;
  }

  /**
   * Creates a new transaction_closed RecordBuilder.
   * @return A new transaction_closed RecordBuilder
   */
  public static accounts.transaction_closed.Builder newBuilder() {
    return new accounts.transaction_closed.Builder();
  }

  /**
   * Creates a new transaction_closed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new transaction_closed RecordBuilder
   */
  public static accounts.transaction_closed.Builder newBuilder(accounts.transaction_closed.Builder other) {
    if (other == null) {
      return new accounts.transaction_closed.Builder();
    } else {
      return new accounts.transaction_closed.Builder(other);
    }
  }

  /**
   * Creates a new transaction_closed RecordBuilder by copying an existing transaction_closed instance.
   * @param other The existing instance to copy.
   * @return A new transaction_closed RecordBuilder
   */
  public static accounts.transaction_closed.Builder newBuilder(accounts.transaction_closed other) {
    if (other == null) {
      return new accounts.transaction_closed.Builder();
    } else {
      return new accounts.transaction_closed.Builder(other);
    }
  }

  /**
   * RecordBuilder for transaction_closed instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<transaction_closed>
    implements org.apache.avro.data.RecordBuilder<transaction_closed> {

    private int attempt;
    private java.lang.String transaction_url;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(accounts.transaction_closed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.attempt)) {
        this.attempt = data().deepCopy(fields()[0].schema(), other.attempt);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transaction_url)) {
        this.transaction_url = data().deepCopy(fields()[1].schema(), other.transaction_url);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing transaction_closed instance
     * @param other The existing instance to copy.
     */
    private Builder(accounts.transaction_closed other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.attempt)) {
        this.attempt = data().deepCopy(fields()[0].schema(), other.attempt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transaction_url)) {
        this.transaction_url = data().deepCopy(fields()[1].schema(), other.transaction_url);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'attempt' field.
      * @return The value.
      */
    public int getAttempt() {
      return attempt;
    }


    /**
      * Sets the value of the 'attempt' field.
      * @param value The value of 'attempt'.
      * @return This builder.
      */
    public accounts.transaction_closed.Builder setAttempt(int value) {
      validate(fields()[0], value);
      this.attempt = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'attempt' field has been set.
      * @return True if the 'attempt' field has been set, false otherwise.
      */
    public boolean hasAttempt() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'attempt' field.
      * @return This builder.
      */
    public accounts.transaction_closed.Builder clearAttempt() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transaction_url' field.
      * @return The value.
      */
    public java.lang.String getTransactionUrl() {
      return transaction_url;
    }


    /**
      * Sets the value of the 'transaction_url' field.
      * @param value The value of 'transaction_url'.
      * @return This builder.
      */
    public accounts.transaction_closed.Builder setTransactionUrl(java.lang.String value) {
      validate(fields()[1], value);
      this.transaction_url = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_url' field has been set.
      * @return True if the 'transaction_url' field has been set, false otherwise.
      */
    public boolean hasTransactionUrl() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transaction_url' field.
      * @return This builder.
      */
    public accounts.transaction_closed.Builder clearTransactionUrl() {
      transaction_url = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public transaction_closed build() {
      try {
        transaction_closed record = new transaction_closed();
        record.attempt = fieldSetFlags()[0] ? this.attempt : (java.lang.Integer) defaultValue(fields()[0]);
        record.transaction_url = fieldSetFlags()[1] ? this.transaction_url : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<transaction_closed>
    WRITER$ = (org.apache.avro.io.DatumWriter<transaction_closed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<transaction_closed>
    READER$ = (org.apache.avro.io.DatumReader<transaction_closed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.attempt);

    out.writeString(this.transaction_url);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.attempt = in.readInt();

      this.transaction_url = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.attempt = in.readInt();
          break;

        case 1:
          this.transaction_url = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










