/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package uk.gov.companieshouse.prosecutioncaseconsumer.avro.models;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ComplianceActionCompleted extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 177480926983723605L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ComplianceActionCompleted\",\"namespace\":\"uk.gov.companieshouse.prosecutioncaseconsumer.avro.models\",\"fields\":[{\"name\":\"compliance_case_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"company_incorporation_number\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"company_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"compliance_user_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"submitted_at\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String compliance_case_id;
  @Deprecated public java.lang.String company_incorporation_number;
  @Deprecated public java.lang.String company_name;
  @Deprecated public java.lang.String compliance_user_id;
  @Deprecated public java.lang.String submitted_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ComplianceActionCompleted() {}

  /**
   * All-args constructor.
   * @param compliance_case_id The new value for compliance_case_id
   * @param company_incorporation_number The new value for company_incorporation_number
   * @param company_name The new value for company_name
   * @param compliance_user_id The new value for compliance_user_id
   * @param submitted_at The new value for submitted_at
   */
  public ComplianceActionCompleted(java.lang.String compliance_case_id, java.lang.String company_incorporation_number, java.lang.String company_name, java.lang.String compliance_user_id, java.lang.String submitted_at) {
    this.compliance_case_id = compliance_case_id;
    this.company_incorporation_number = company_incorporation_number;
    this.company_name = company_name;
    this.compliance_user_id = compliance_user_id;
    this.submitted_at = submitted_at;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return compliance_case_id;
    case 1: return company_incorporation_number;
    case 2: return company_name;
    case 3: return compliance_user_id;
    case 4: return submitted_at;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: compliance_case_id = (java.lang.String)value$; break;
    case 1: company_incorporation_number = (java.lang.String)value$; break;
    case 2: company_name = (java.lang.String)value$; break;
    case 3: compliance_user_id = (java.lang.String)value$; break;
    case 4: submitted_at = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'compliance_case_id' field.
   * @return The value of the 'compliance_case_id' field.
   */
  public java.lang.String getComplianceCaseId() {
    return compliance_case_id;
  }

  /**
   * Sets the value of the 'compliance_case_id' field.
   * @param value the value to set.
   */
  public void setComplianceCaseId(java.lang.String value) {
    this.compliance_case_id = value;
  }

  /**
   * Gets the value of the 'company_incorporation_number' field.
   * @return The value of the 'company_incorporation_number' field.
   */
  public java.lang.String getCompanyIncorporationNumber() {
    return company_incorporation_number;
  }

  /**
   * Sets the value of the 'company_incorporation_number' field.
   * @param value the value to set.
   */
  public void setCompanyIncorporationNumber(java.lang.String value) {
    this.company_incorporation_number = value;
  }

  /**
   * Gets the value of the 'company_name' field.
   * @return The value of the 'company_name' field.
   */
  public java.lang.String getCompanyName() {
    return company_name;
  }

  /**
   * Sets the value of the 'company_name' field.
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.String value) {
    this.company_name = value;
  }

  /**
   * Gets the value of the 'compliance_user_id' field.
   * @return The value of the 'compliance_user_id' field.
   */
  public java.lang.String getComplianceUserId() {
    return compliance_user_id;
  }

  /**
   * Sets the value of the 'compliance_user_id' field.
   * @param value the value to set.
   */
  public void setComplianceUserId(java.lang.String value) {
    this.compliance_user_id = value;
  }

  /**
   * Gets the value of the 'submitted_at' field.
   * @return The value of the 'submitted_at' field.
   */
  public java.lang.String getSubmittedAt() {
    return submitted_at;
  }

  /**
   * Sets the value of the 'submitted_at' field.
   * @param value the value to set.
   */
  public void setSubmittedAt(java.lang.String value) {
    this.submitted_at = value;
  }

  /**
   * Creates a new ComplianceActionCompleted RecordBuilder.
   * @return A new ComplianceActionCompleted RecordBuilder
   */
  public static uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder newBuilder() {
    return new uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder();
  }

  /**
   * Creates a new ComplianceActionCompleted RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ComplianceActionCompleted RecordBuilder
   */
  public static uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder newBuilder(uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder other) {
    return new uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder(other);
  }

  /**
   * Creates a new ComplianceActionCompleted RecordBuilder by copying an existing ComplianceActionCompleted instance.
   * @param other The existing instance to copy.
   * @return A new ComplianceActionCompleted RecordBuilder
   */
  public static uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder newBuilder(uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted other) {
    return new uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder(other);
  }

  /**
   * RecordBuilder for ComplianceActionCompleted instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ComplianceActionCompleted>
    implements org.apache.avro.data.RecordBuilder<ComplianceActionCompleted> {

    private java.lang.String compliance_case_id;
    private java.lang.String company_incorporation_number;
    private java.lang.String company_name;
    private java.lang.String compliance_user_id;
    private java.lang.String submitted_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.compliance_case_id)) {
        this.compliance_case_id = data().deepCopy(fields()[0].schema(), other.compliance_case_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.company_incorporation_number)) {
        this.company_incorporation_number = data().deepCopy(fields()[1].schema(), other.company_incorporation_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.company_name)) {
        this.company_name = data().deepCopy(fields()[2].schema(), other.company_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.compliance_user_id)) {
        this.compliance_user_id = data().deepCopy(fields()[3].schema(), other.compliance_user_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.submitted_at)) {
        this.submitted_at = data().deepCopy(fields()[4].schema(), other.submitted_at);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ComplianceActionCompleted instance
     * @param other The existing instance to copy.
     */
    private Builder(uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.compliance_case_id)) {
        this.compliance_case_id = data().deepCopy(fields()[0].schema(), other.compliance_case_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.company_incorporation_number)) {
        this.company_incorporation_number = data().deepCopy(fields()[1].schema(), other.company_incorporation_number);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.company_name)) {
        this.company_name = data().deepCopy(fields()[2].schema(), other.company_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.compliance_user_id)) {
        this.compliance_user_id = data().deepCopy(fields()[3].schema(), other.compliance_user_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.submitted_at)) {
        this.submitted_at = data().deepCopy(fields()[4].schema(), other.submitted_at);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'compliance_case_id' field.
      * @return The value.
      */
    public java.lang.String getComplianceCaseId() {
      return compliance_case_id;
    }

    /**
      * Sets the value of the 'compliance_case_id' field.
      * @param value The value of 'compliance_case_id'.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder setComplianceCaseId(java.lang.String value) {
      validate(fields()[0], value);
      this.compliance_case_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'compliance_case_id' field has been set.
      * @return True if the 'compliance_case_id' field has been set, false otherwise.
      */
    public boolean hasComplianceCaseId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'compliance_case_id' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder clearComplianceCaseId() {
      compliance_case_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'company_incorporation_number' field.
      * @return The value.
      */
    public java.lang.String getCompanyIncorporationNumber() {
      return company_incorporation_number;
    }

    /**
      * Sets the value of the 'company_incorporation_number' field.
      * @param value The value of 'company_incorporation_number'.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder setCompanyIncorporationNumber(java.lang.String value) {
      validate(fields()[1], value);
      this.company_incorporation_number = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'company_incorporation_number' field has been set.
      * @return True if the 'company_incorporation_number' field has been set, false otherwise.
      */
    public boolean hasCompanyIncorporationNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'company_incorporation_number' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder clearCompanyIncorporationNumber() {
      company_incorporation_number = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'company_name' field.
      * @return The value.
      */
    public java.lang.String getCompanyName() {
      return company_name;
    }

    /**
      * Sets the value of the 'company_name' field.
      * @param value The value of 'company_name'.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder setCompanyName(java.lang.String value) {
      validate(fields()[2], value);
      this.company_name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'company_name' field has been set.
      * @return True if the 'company_name' field has been set, false otherwise.
      */
    public boolean hasCompanyName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'company_name' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder clearCompanyName() {
      company_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'compliance_user_id' field.
      * @return The value.
      */
    public java.lang.String getComplianceUserId() {
      return compliance_user_id;
    }

    /**
      * Sets the value of the 'compliance_user_id' field.
      * @param value The value of 'compliance_user_id'.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder setComplianceUserId(java.lang.String value) {
      validate(fields()[3], value);
      this.compliance_user_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'compliance_user_id' field has been set.
      * @return True if the 'compliance_user_id' field has been set, false otherwise.
      */
    public boolean hasComplianceUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'compliance_user_id' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder clearComplianceUserId() {
      compliance_user_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'submitted_at' field.
      * @return The value.
      */
    public java.lang.String getSubmittedAt() {
      return submitted_at;
    }

    /**
      * Sets the value of the 'submitted_at' field.
      * @param value The value of 'submitted_at'.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder setSubmittedAt(java.lang.String value) {
      validate(fields()[4], value);
      this.submitted_at = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'submitted_at' field has been set.
      * @return True if the 'submitted_at' field has been set, false otherwise.
      */
    public boolean hasSubmittedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'submitted_at' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.prosecutioncaseconsumer.avro.models.ComplianceActionCompleted.Builder clearSubmittedAt() {
      submitted_at = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public ComplianceActionCompleted build() {
      try {
        ComplianceActionCompleted record = new ComplianceActionCompleted();
        record.compliance_case_id = fieldSetFlags()[0] ? this.compliance_case_id : (java.lang.String) defaultValue(fields()[0]);
        record.company_incorporation_number = fieldSetFlags()[1] ? this.company_incorporation_number : (java.lang.String) defaultValue(fields()[1]);
        record.company_name = fieldSetFlags()[2] ? this.company_name : (java.lang.String) defaultValue(fields()[2]);
        record.compliance_user_id = fieldSetFlags()[3] ? this.compliance_user_id : (java.lang.String) defaultValue(fields()[3]);
        record.submitted_at = fieldSetFlags()[4] ? this.submitted_at : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
