/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package email;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class message_send extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -865823888133847509L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"message_send\",\"namespace\":\"email\",\"fields\":[{\"name\":\"app_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"message_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"message_type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"data\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"user_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"created_at\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<message_send> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<message_send> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<message_send> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<message_send> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<message_send> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this message_send to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a message_send from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a message_send instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static message_send fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String app_id;
  private java.lang.String message_id;
  private java.lang.String message_type;
  private java.lang.String data;
  private java.lang.String user_id;
  private java.lang.String created_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public message_send() {}

  /**
   * All-args constructor.
   * @param app_id The new value for app_id
   * @param message_id The new value for message_id
   * @param message_type The new value for message_type
   * @param data The new value for data
   * @param user_id The new value for user_id
   * @param created_at The new value for created_at
   */
  public message_send(java.lang.String app_id, java.lang.String message_id, java.lang.String message_type, java.lang.String data, java.lang.String user_id, java.lang.String created_at) {
    this.app_id = app_id;
    this.message_id = message_id;
    this.message_type = message_type;
    this.data = data;
    this.user_id = user_id;
    this.created_at = created_at;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return app_id;
    case 1: return message_id;
    case 2: return message_type;
    case 3: return data;
    case 4: return user_id;
    case 5: return created_at;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: app_id = value$ != null ? value$.toString() : null; break;
    case 1: message_id = value$ != null ? value$.toString() : null; break;
    case 2: message_type = value$ != null ? value$.toString() : null; break;
    case 3: data = value$ != null ? value$.toString() : null; break;
    case 4: user_id = value$ != null ? value$.toString() : null; break;
    case 5: created_at = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'app_id' field.
   * @return The value of the 'app_id' field.
   */
  public java.lang.String getAppId() {
    return app_id;
  }


  /**
   * Sets the value of the 'app_id' field.
   * @param value the value to set.
   */
  public void setAppId(java.lang.String value) {
    this.app_id = value;
  }

  /**
   * Gets the value of the 'message_id' field.
   * @return The value of the 'message_id' field.
   */
  public java.lang.String getMessageId() {
    return message_id;
  }


  /**
   * Sets the value of the 'message_id' field.
   * @param value the value to set.
   */
  public void setMessageId(java.lang.String value) {
    this.message_id = value;
  }

  /**
   * Gets the value of the 'message_type' field.
   * @return The value of the 'message_type' field.
   */
  public java.lang.String getMessageType() {
    return message_type;
  }


  /**
   * Sets the value of the 'message_type' field.
   * @param value the value to set.
   */
  public void setMessageType(java.lang.String value) {
    this.message_type = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.lang.String getData() {
    return data;
  }


  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.lang.String value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.String getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.lang.String getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.String value) {
    this.created_at = value;
  }

  /**
   * Creates a new message_send RecordBuilder.
   * @return A new message_send RecordBuilder
   */
  public static email.message_send.Builder newBuilder() {
    return new email.message_send.Builder();
  }

  /**
   * Creates a new message_send RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new message_send RecordBuilder
   */
  public static email.message_send.Builder newBuilder(email.message_send.Builder other) {
    if (other == null) {
      return new email.message_send.Builder();
    } else {
      return new email.message_send.Builder(other);
    }
  }

  /**
   * Creates a new message_send RecordBuilder by copying an existing message_send instance.
   * @param other The existing instance to copy.
   * @return A new message_send RecordBuilder
   */
  public static email.message_send.Builder newBuilder(email.message_send other) {
    if (other == null) {
      return new email.message_send.Builder();
    } else {
      return new email.message_send.Builder(other);
    }
  }

  /**
   * RecordBuilder for message_send instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<message_send>
    implements org.apache.avro.data.RecordBuilder<message_send> {

    private java.lang.String app_id;
    private java.lang.String message_id;
    private java.lang.String message_type;
    private java.lang.String data;
    private java.lang.String user_id;
    private java.lang.String created_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(email.message_send.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.app_id)) {
        this.app_id = data().deepCopy(fields()[0].schema(), other.app_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.message_id)) {
        this.message_id = data().deepCopy(fields()[1].schema(), other.message_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.message_type)) {
        this.message_type = data().deepCopy(fields()[2].schema(), other.message_type);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.data)) {
        this.data = data().deepCopy(fields()[3].schema(), other.data);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.user_id)) {
        this.user_id = data().deepCopy(fields()[4].schema(), other.user_id);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.created_at)) {
        this.created_at = data().deepCopy(fields()[5].schema(), other.created_at);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing message_send instance
     * @param other The existing instance to copy.
     */
    private Builder(email.message_send other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.app_id)) {
        this.app_id = data().deepCopy(fields()[0].schema(), other.app_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message_id)) {
        this.message_id = data().deepCopy(fields()[1].schema(), other.message_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.message_type)) {
        this.message_type = data().deepCopy(fields()[2].schema(), other.message_type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.data)) {
        this.data = data().deepCopy(fields()[3].schema(), other.data);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.user_id)) {
        this.user_id = data().deepCopy(fields()[4].schema(), other.user_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.created_at)) {
        this.created_at = data().deepCopy(fields()[5].schema(), other.created_at);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'app_id' field.
      * @return The value.
      */
    public java.lang.String getAppId() {
      return app_id;
    }


    /**
      * Sets the value of the 'app_id' field.
      * @param value The value of 'app_id'.
      * @return This builder.
      */
    public email.message_send.Builder setAppId(java.lang.String value) {
      validate(fields()[0], value);
      this.app_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'app_id' field has been set.
      * @return True if the 'app_id' field has been set, false otherwise.
      */
    public boolean hasAppId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'app_id' field.
      * @return This builder.
      */
    public email.message_send.Builder clearAppId() {
      app_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'message_id' field.
      * @return The value.
      */
    public java.lang.String getMessageId() {
      return message_id;
    }


    /**
      * Sets the value of the 'message_id' field.
      * @param value The value of 'message_id'.
      * @return This builder.
      */
    public email.message_send.Builder setMessageId(java.lang.String value) {
      validate(fields()[1], value);
      this.message_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'message_id' field has been set.
      * @return True if the 'message_id' field has been set, false otherwise.
      */
    public boolean hasMessageId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'message_id' field.
      * @return This builder.
      */
    public email.message_send.Builder clearMessageId() {
      message_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'message_type' field.
      * @return The value.
      */
    public java.lang.String getMessageType() {
      return message_type;
    }


    /**
      * Sets the value of the 'message_type' field.
      * @param value The value of 'message_type'.
      * @return This builder.
      */
    public email.message_send.Builder setMessageType(java.lang.String value) {
      validate(fields()[2], value);
      this.message_type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'message_type' field has been set.
      * @return True if the 'message_type' field has been set, false otherwise.
      */
    public boolean hasMessageType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'message_type' field.
      * @return This builder.
      */
    public email.message_send.Builder clearMessageType() {
      message_type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.lang.String getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public email.message_send.Builder setData(java.lang.String value) {
      validate(fields()[3], value);
      this.data = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public email.message_send.Builder clearData() {
      data = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public email.message_send.Builder setUserId(java.lang.String value) {
      validate(fields()[4], value);
      this.user_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public email.message_send.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.lang.String getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public email.message_send.Builder setCreatedAt(java.lang.String value) {
      validate(fields()[5], value);
      this.created_at = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public email.message_send.Builder clearCreatedAt() {
      created_at = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public message_send build() {
      try {
        message_send record = new message_send();
        record.app_id = fieldSetFlags()[0] ? this.app_id : (java.lang.String) defaultValue(fields()[0]);
        record.message_id = fieldSetFlags()[1] ? this.message_id : (java.lang.String) defaultValue(fields()[1]);
        record.message_type = fieldSetFlags()[2] ? this.message_type : (java.lang.String) defaultValue(fields()[2]);
        record.data = fieldSetFlags()[3] ? this.data : (java.lang.String) defaultValue(fields()[3]);
        record.user_id = fieldSetFlags()[4] ? this.user_id : (java.lang.String) defaultValue(fields()[4]);
        record.created_at = fieldSetFlags()[5] ? this.created_at : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<message_send>
    WRITER$ = (org.apache.avro.io.DatumWriter<message_send>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<message_send>
    READER$ = (org.apache.avro.io.DatumReader<message_send>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.app_id);

    out.writeString(this.message_id);

    out.writeString(this.message_type);

    out.writeString(this.data);

    out.writeString(this.user_id);

    out.writeString(this.created_at);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.app_id = in.readString();

      this.message_id = in.readString();

      this.message_type = in.readString();

      this.data = in.readString();

      this.user_id = in.readString();

      this.created_at = in.readString();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.app_id = in.readString();
          break;

        case 1:
          this.message_id = in.readString();
          break;

        case 2:
          this.message_type = in.readString();
          break;

        case 3:
          this.data = in.readString();
          break;

        case 4:
          this.user_id = in.readString();
          break;

        case 5:
          this.created_at = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










