/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package payments;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class payment_processed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4997048472080056986L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"payment_processed\",\"namespace\":\"payments\",\"fields\":[{\"name\":\"attempt\",\"type\":\"int\"},{\"name\":\"payment_resource_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"refund_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<payment_processed> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<payment_processed> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<payment_processed> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<payment_processed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<payment_processed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this payment_processed to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a payment_processed from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a payment_processed instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static payment_processed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int attempt;
  private java.lang.String payment_resource_id;
  private java.lang.String refund_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public payment_processed() {}

  /**
   * All-args constructor.
   * @param attempt The new value for attempt
   * @param payment_resource_id The new value for payment_resource_id
   * @param refund_id The new value for refund_id
   */
  public payment_processed(java.lang.Integer attempt, java.lang.String payment_resource_id, java.lang.String refund_id) {
    this.attempt = attempt;
    this.payment_resource_id = payment_resource_id;
    this.refund_id = refund_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return attempt;
    case 1: return payment_resource_id;
    case 2: return refund_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: attempt = (java.lang.Integer)value$; break;
    case 1: payment_resource_id = value$ != null ? value$.toString() : null; break;
    case 2: refund_id = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'attempt' field.
   * @return The value of the 'attempt' field.
   */
  public int getAttempt() {
    return attempt;
  }


  /**
   * Sets the value of the 'attempt' field.
   * @param value the value to set.
   */
  public void setAttempt(int value) {
    this.attempt = value;
  }

  /**
   * Gets the value of the 'payment_resource_id' field.
   * @return The value of the 'payment_resource_id' field.
   */
  public java.lang.String getPaymentResourceId() {
    return payment_resource_id;
  }


  /**
   * Sets the value of the 'payment_resource_id' field.
   * @param value the value to set.
   */
  public void setPaymentResourceId(java.lang.String value) {
    this.payment_resource_id = value;
  }

  /**
   * Gets the value of the 'refund_id' field.
   * @return The value of the 'refund_id' field.
   */
  public java.lang.String getRefundId() {
    return refund_id;
  }


  /**
   * Sets the value of the 'refund_id' field.
   * @param value the value to set.
   */
  public void setRefundId(java.lang.String value) {
    this.refund_id = value;
  }

  /**
   * Creates a new payment_processed RecordBuilder.
   * @return A new payment_processed RecordBuilder
   */
  public static payments.payment_processed.Builder newBuilder() {
    return new payments.payment_processed.Builder();
  }

  /**
   * Creates a new payment_processed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new payment_processed RecordBuilder
   */
  public static payments.payment_processed.Builder newBuilder(payments.payment_processed.Builder other) {
    if (other == null) {
      return new payments.payment_processed.Builder();
    } else {
      return new payments.payment_processed.Builder(other);
    }
  }

  /**
   * Creates a new payment_processed RecordBuilder by copying an existing payment_processed instance.
   * @param other The existing instance to copy.
   * @return A new payment_processed RecordBuilder
   */
  public static payments.payment_processed.Builder newBuilder(payments.payment_processed other) {
    if (other == null) {
      return new payments.payment_processed.Builder();
    } else {
      return new payments.payment_processed.Builder(other);
    }
  }

  /**
   * RecordBuilder for payment_processed instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<payment_processed>
    implements org.apache.avro.data.RecordBuilder<payment_processed> {

    private int attempt;
    private java.lang.String payment_resource_id;
    private java.lang.String refund_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(payments.payment_processed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.attempt)) {
        this.attempt = data().deepCopy(fields()[0].schema(), other.attempt);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.payment_resource_id)) {
        this.payment_resource_id = data().deepCopy(fields()[1].schema(), other.payment_resource_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.refund_id)) {
        this.refund_id = data().deepCopy(fields()[2].schema(), other.refund_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing payment_processed instance
     * @param other The existing instance to copy.
     */
    private Builder(payments.payment_processed other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.attempt)) {
        this.attempt = data().deepCopy(fields()[0].schema(), other.attempt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.payment_resource_id)) {
        this.payment_resource_id = data().deepCopy(fields()[1].schema(), other.payment_resource_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.refund_id)) {
        this.refund_id = data().deepCopy(fields()[2].schema(), other.refund_id);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'attempt' field.
      * @return The value.
      */
    public int getAttempt() {
      return attempt;
    }


    /**
      * Sets the value of the 'attempt' field.
      * @param value The value of 'attempt'.
      * @return This builder.
      */
    public payments.payment_processed.Builder setAttempt(int value) {
      validate(fields()[0], value);
      this.attempt = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'attempt' field has been set.
      * @return True if the 'attempt' field has been set, false otherwise.
      */
    public boolean hasAttempt() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'attempt' field.
      * @return This builder.
      */
    public payments.payment_processed.Builder clearAttempt() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_resource_id' field.
      * @return The value.
      */
    public java.lang.String getPaymentResourceId() {
      return payment_resource_id;
    }


    /**
      * Sets the value of the 'payment_resource_id' field.
      * @param value The value of 'payment_resource_id'.
      * @return This builder.
      */
    public payments.payment_processed.Builder setPaymentResourceId(java.lang.String value) {
      validate(fields()[1], value);
      this.payment_resource_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_resource_id' field has been set.
      * @return True if the 'payment_resource_id' field has been set, false otherwise.
      */
    public boolean hasPaymentResourceId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'payment_resource_id' field.
      * @return This builder.
      */
    public payments.payment_processed.Builder clearPaymentResourceId() {
      payment_resource_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'refund_id' field.
      * @return The value.
      */
    public java.lang.String getRefundId() {
      return refund_id;
    }


    /**
      * Sets the value of the 'refund_id' field.
      * @param value The value of 'refund_id'.
      * @return This builder.
      */
    public payments.payment_processed.Builder setRefundId(java.lang.String value) {
      validate(fields()[2], value);
      this.refund_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'refund_id' field has been set.
      * @return True if the 'refund_id' field has been set, false otherwise.
      */
    public boolean hasRefundId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'refund_id' field.
      * @return This builder.
      */
    public payments.payment_processed.Builder clearRefundId() {
      refund_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public payment_processed build() {
      try {
        payment_processed record = new payment_processed();
        record.attempt = fieldSetFlags()[0] ? this.attempt : (java.lang.Integer) defaultValue(fields()[0]);
        record.payment_resource_id = fieldSetFlags()[1] ? this.payment_resource_id : (java.lang.String) defaultValue(fields()[1]);
        record.refund_id = fieldSetFlags()[2] ? this.refund_id : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<payment_processed>
    WRITER$ = (org.apache.avro.io.DatumWriter<payment_processed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<payment_processed>
    READER$ = (org.apache.avro.io.DatumReader<payment_processed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.attempt);

    out.writeString(this.payment_resource_id);

    if (this.refund_id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.refund_id);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.attempt = in.readInt();

      this.payment_resource_id = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.refund_id = null;
      } else {
        this.refund_id = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.attempt = in.readInt();
          break;

        case 1:
          this.payment_resource_id = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.refund_id = null;
          } else {
            this.refund_id = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










