/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package payments;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class refund_request extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3216425918059802299L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"refund_request\",\"namespace\":\"payments\",\"fields\":[{\"name\":\"attempt\",\"type\":\"int\"},{\"name\":\"payment_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"refund_amount\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"refund_reference\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<refund_request> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<refund_request> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<refund_request> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<refund_request> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<refund_request> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this refund_request to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a refund_request from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a refund_request instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static refund_request fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int attempt;
  private java.lang.String payment_id;
  private java.lang.String refund_amount;
  private java.lang.String refund_reference;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public refund_request() {}

  /**
   * All-args constructor.
   * @param attempt The new value for attempt
   * @param payment_id The new value for payment_id
   * @param refund_amount The new value for refund_amount
   * @param refund_reference The new value for refund_reference
   */
  public refund_request(java.lang.Integer attempt, java.lang.String payment_id, java.lang.String refund_amount, java.lang.String refund_reference) {
    this.attempt = attempt;
    this.payment_id = payment_id;
    this.refund_amount = refund_amount;
    this.refund_reference = refund_reference;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return attempt;
    case 1: return payment_id;
    case 2: return refund_amount;
    case 3: return refund_reference;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: attempt = (java.lang.Integer)value$; break;
    case 1: payment_id = value$ != null ? value$.toString() : null; break;
    case 2: refund_amount = value$ != null ? value$.toString() : null; break;
    case 3: refund_reference = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'attempt' field.
   * @return The value of the 'attempt' field.
   */
  public int getAttempt() {
    return attempt;
  }


  /**
   * Sets the value of the 'attempt' field.
   * @param value the value to set.
   */
  public void setAttempt(int value) {
    this.attempt = value;
  }

  /**
   * Gets the value of the 'payment_id' field.
   * @return The value of the 'payment_id' field.
   */
  public java.lang.String getPaymentId() {
    return payment_id;
  }


  /**
   * Sets the value of the 'payment_id' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.String value) {
    this.payment_id = value;
  }

  /**
   * Gets the value of the 'refund_amount' field.
   * @return The value of the 'refund_amount' field.
   */
  public java.lang.String getRefundAmount() {
    return refund_amount;
  }


  /**
   * Sets the value of the 'refund_amount' field.
   * @param value the value to set.
   */
  public void setRefundAmount(java.lang.String value) {
    this.refund_amount = value;
  }

  /**
   * Gets the value of the 'refund_reference' field.
   * @return The value of the 'refund_reference' field.
   */
  public java.lang.String getRefundReference() {
    return refund_reference;
  }


  /**
   * Sets the value of the 'refund_reference' field.
   * @param value the value to set.
   */
  public void setRefundReference(java.lang.String value) {
    this.refund_reference = value;
  }

  /**
   * Creates a new refund_request RecordBuilder.
   * @return A new refund_request RecordBuilder
   */
  public static payments.refund_request.Builder newBuilder() {
    return new payments.refund_request.Builder();
  }

  /**
   * Creates a new refund_request RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new refund_request RecordBuilder
   */
  public static payments.refund_request.Builder newBuilder(payments.refund_request.Builder other) {
    if (other == null) {
      return new payments.refund_request.Builder();
    } else {
      return new payments.refund_request.Builder(other);
    }
  }

  /**
   * Creates a new refund_request RecordBuilder by copying an existing refund_request instance.
   * @param other The existing instance to copy.
   * @return A new refund_request RecordBuilder
   */
  public static payments.refund_request.Builder newBuilder(payments.refund_request other) {
    if (other == null) {
      return new payments.refund_request.Builder();
    } else {
      return new payments.refund_request.Builder(other);
    }
  }

  /**
   * RecordBuilder for refund_request instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<refund_request>
    implements org.apache.avro.data.RecordBuilder<refund_request> {

    private int attempt;
    private java.lang.String payment_id;
    private java.lang.String refund_amount;
    private java.lang.String refund_reference;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(payments.refund_request.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.attempt)) {
        this.attempt = data().deepCopy(fields()[0].schema(), other.attempt);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.payment_id)) {
        this.payment_id = data().deepCopy(fields()[1].schema(), other.payment_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.refund_amount)) {
        this.refund_amount = data().deepCopy(fields()[2].schema(), other.refund_amount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.refund_reference)) {
        this.refund_reference = data().deepCopy(fields()[3].schema(), other.refund_reference);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing refund_request instance
     * @param other The existing instance to copy.
     */
    private Builder(payments.refund_request other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.attempt)) {
        this.attempt = data().deepCopy(fields()[0].schema(), other.attempt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.payment_id)) {
        this.payment_id = data().deepCopy(fields()[1].schema(), other.payment_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.refund_amount)) {
        this.refund_amount = data().deepCopy(fields()[2].schema(), other.refund_amount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.refund_reference)) {
        this.refund_reference = data().deepCopy(fields()[3].schema(), other.refund_reference);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'attempt' field.
      * @return The value.
      */
    public int getAttempt() {
      return attempt;
    }


    /**
      * Sets the value of the 'attempt' field.
      * @param value The value of 'attempt'.
      * @return This builder.
      */
    public payments.refund_request.Builder setAttempt(int value) {
      validate(fields()[0], value);
      this.attempt = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'attempt' field has been set.
      * @return True if the 'attempt' field has been set, false otherwise.
      */
    public boolean hasAttempt() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'attempt' field.
      * @return This builder.
      */
    public payments.refund_request.Builder clearAttempt() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_id' field.
      * @return The value.
      */
    public java.lang.String getPaymentId() {
      return payment_id;
    }


    /**
      * Sets the value of the 'payment_id' field.
      * @param value The value of 'payment_id'.
      * @return This builder.
      */
    public payments.refund_request.Builder setPaymentId(java.lang.String value) {
      validate(fields()[1], value);
      this.payment_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_id' field has been set.
      * @return True if the 'payment_id' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'payment_id' field.
      * @return This builder.
      */
    public payments.refund_request.Builder clearPaymentId() {
      payment_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'refund_amount' field.
      * @return The value.
      */
    public java.lang.String getRefundAmount() {
      return refund_amount;
    }


    /**
      * Sets the value of the 'refund_amount' field.
      * @param value The value of 'refund_amount'.
      * @return This builder.
      */
    public payments.refund_request.Builder setRefundAmount(java.lang.String value) {
      validate(fields()[2], value);
      this.refund_amount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'refund_amount' field has been set.
      * @return True if the 'refund_amount' field has been set, false otherwise.
      */
    public boolean hasRefundAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'refund_amount' field.
      * @return This builder.
      */
    public payments.refund_request.Builder clearRefundAmount() {
      refund_amount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'refund_reference' field.
      * @return The value.
      */
    public java.lang.String getRefundReference() {
      return refund_reference;
    }


    /**
      * Sets the value of the 'refund_reference' field.
      * @param value The value of 'refund_reference'.
      * @return This builder.
      */
    public payments.refund_request.Builder setRefundReference(java.lang.String value) {
      validate(fields()[3], value);
      this.refund_reference = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'refund_reference' field has been set.
      * @return True if the 'refund_reference' field has been set, false otherwise.
      */
    public boolean hasRefundReference() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'refund_reference' field.
      * @return This builder.
      */
    public payments.refund_request.Builder clearRefundReference() {
      refund_reference = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public refund_request build() {
      try {
        refund_request record = new refund_request();
        record.attempt = fieldSetFlags()[0] ? this.attempt : (java.lang.Integer) defaultValue(fields()[0]);
        record.payment_id = fieldSetFlags()[1] ? this.payment_id : (java.lang.String) defaultValue(fields()[1]);
        record.refund_amount = fieldSetFlags()[2] ? this.refund_amount : (java.lang.String) defaultValue(fields()[2]);
        record.refund_reference = fieldSetFlags()[3] ? this.refund_reference : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<refund_request>
    WRITER$ = (org.apache.avro.io.DatumWriter<refund_request>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<refund_request>
    READER$ = (org.apache.avro.io.DatumReader<refund_request>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.attempt);

    out.writeString(this.payment_id);

    out.writeString(this.refund_amount);

    out.writeString(this.refund_reference);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.attempt = in.readInt();

      this.payment_id = in.readString();

      this.refund_amount = in.readString();

      this.refund_reference = in.readString();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.attempt = in.readInt();
          break;

        case 1:
          this.payment_id = in.readString();
          break;

        case 2:
          this.refund_amount = in.readString();
          break;

        case 3:
          this.refund_reference = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










