/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package monitor;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class filing extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1745532536035122325L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"filing\",\"namespace\":\"monitor\",\"fields\":[{\"name\":\"data\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"kind\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"notified_at\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"user_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<filing> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<filing> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<filing> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<filing> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<filing> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this filing to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a filing from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a filing instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static filing fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String data;
  private java.lang.String kind;
  private java.lang.String notified_at;
  private java.lang.String user_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public filing() {}

  /**
   * All-args constructor.
   * @param data The new value for data
   * @param kind The new value for kind
   * @param notified_at The new value for notified_at
   * @param user_id The new value for user_id
   */
  public filing(java.lang.String data, java.lang.String kind, java.lang.String notified_at, java.lang.String user_id) {
    this.data = data;
    this.kind = kind;
    this.notified_at = notified_at;
    this.user_id = user_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    case 1: return kind;
    case 2: return notified_at;
    case 3: return user_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = value$ != null ? value$.toString() : null; break;
    case 1: kind = value$ != null ? value$.toString() : null; break;
    case 2: notified_at = value$ != null ? value$.toString() : null; break;
    case 3: user_id = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.lang.String getData() {
    return data;
  }


  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.lang.String value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'kind' field.
   * @return The value of the 'kind' field.
   */
  public java.lang.String getKind() {
    return kind;
  }


  /**
   * Sets the value of the 'kind' field.
   * @param value the value to set.
   */
  public void setKind(java.lang.String value) {
    this.kind = value;
  }

  /**
   * Gets the value of the 'notified_at' field.
   * @return The value of the 'notified_at' field.
   */
  public java.lang.String getNotifiedAt() {
    return notified_at;
  }


  /**
   * Sets the value of the 'notified_at' field.
   * @param value the value to set.
   */
  public void setNotifiedAt(java.lang.String value) {
    this.notified_at = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.String getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.user_id = value;
  }

  /**
   * Creates a new filing RecordBuilder.
   * @return A new filing RecordBuilder
   */
  public static monitor.filing.Builder newBuilder() {
    return new monitor.filing.Builder();
  }

  /**
   * Creates a new filing RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new filing RecordBuilder
   */
  public static monitor.filing.Builder newBuilder(monitor.filing.Builder other) {
    if (other == null) {
      return new monitor.filing.Builder();
    } else {
      return new monitor.filing.Builder(other);
    }
  }

  /**
   * Creates a new filing RecordBuilder by copying an existing filing instance.
   * @param other The existing instance to copy.
   * @return A new filing RecordBuilder
   */
  public static monitor.filing.Builder newBuilder(monitor.filing other) {
    if (other == null) {
      return new monitor.filing.Builder();
    } else {
      return new monitor.filing.Builder(other);
    }
  }

  /**
   * RecordBuilder for filing instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<filing>
    implements org.apache.avro.data.RecordBuilder<filing> {

    private java.lang.String data;
    private java.lang.String kind;
    private java.lang.String notified_at;
    private java.lang.String user_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(monitor.filing.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.kind)) {
        this.kind = data().deepCopy(fields()[1].schema(), other.kind);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.notified_at)) {
        this.notified_at = data().deepCopy(fields()[2].schema(), other.notified_at);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.user_id)) {
        this.user_id = data().deepCopy(fields()[3].schema(), other.user_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing filing instance
     * @param other The existing instance to copy.
     */
    private Builder(monitor.filing other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.kind)) {
        this.kind = data().deepCopy(fields()[1].schema(), other.kind);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.notified_at)) {
        this.notified_at = data().deepCopy(fields()[2].schema(), other.notified_at);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.user_id)) {
        this.user_id = data().deepCopy(fields()[3].schema(), other.user_id);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.lang.String getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public monitor.filing.Builder setData(java.lang.String value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public monitor.filing.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'kind' field.
      * @return The value.
      */
    public java.lang.String getKind() {
      return kind;
    }


    /**
      * Sets the value of the 'kind' field.
      * @param value The value of 'kind'.
      * @return This builder.
      */
    public monitor.filing.Builder setKind(java.lang.String value) {
      validate(fields()[1], value);
      this.kind = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'kind' field has been set.
      * @return True if the 'kind' field has been set, false otherwise.
      */
    public boolean hasKind() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'kind' field.
      * @return This builder.
      */
    public monitor.filing.Builder clearKind() {
      kind = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'notified_at' field.
      * @return The value.
      */
    public java.lang.String getNotifiedAt() {
      return notified_at;
    }


    /**
      * Sets the value of the 'notified_at' field.
      * @param value The value of 'notified_at'.
      * @return This builder.
      */
    public monitor.filing.Builder setNotifiedAt(java.lang.String value) {
      validate(fields()[2], value);
      this.notified_at = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'notified_at' field has been set.
      * @return True if the 'notified_at' field has been set, false otherwise.
      */
    public boolean hasNotifiedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'notified_at' field.
      * @return This builder.
      */
    public monitor.filing.Builder clearNotifiedAt() {
      notified_at = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public monitor.filing.Builder setUserId(java.lang.String value) {
      validate(fields()[3], value);
      this.user_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public monitor.filing.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public filing build() {
      try {
        filing record = new filing();
        record.data = fieldSetFlags()[0] ? this.data : (java.lang.String) defaultValue(fields()[0]);
        record.kind = fieldSetFlags()[1] ? this.kind : (java.lang.String) defaultValue(fields()[1]);
        record.notified_at = fieldSetFlags()[2] ? this.notified_at : (java.lang.String) defaultValue(fields()[2]);
        record.user_id = fieldSetFlags()[3] ? this.user_id : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<filing>
    WRITER$ = (org.apache.avro.io.DatumWriter<filing>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<filing>
    READER$ = (org.apache.avro.io.DatumReader<filing>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.data);

    out.writeString(this.kind);

    out.writeString(this.notified_at);

    out.writeString(this.user_id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.data = in.readString();

      this.kind = in.readString();

      this.notified_at = in.readString();

      this.user_id = in.readString();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.data = in.readString();
          break;

        case 1:
          this.kind = in.readString();
          break;

        case 2:
          this.notified_at = in.readString();
          break;

        case 3:
          this.user_id = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










