/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package uk.gov.companieshouse.filing.processed;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SubmissionRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4769820291104592895L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SubmissionRecord\",\"namespace\":\"uk.gov.companieshouse.filing.processed\",\"fields\":[{\"name\":\"transaction_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String transaction_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SubmissionRecord() {}

  /**
   * All-args constructor.
   * @param transaction_id The new value for transaction_id
   */
  public SubmissionRecord(java.lang.String transaction_id) {
    this.transaction_id = transaction_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transaction_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transaction_id = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'transaction_id' field.
   * @return The value of the 'transaction_id' field.
   */
  public java.lang.String getTransactionId() {
    return transaction_id;
  }

  /**
   * Sets the value of the 'transaction_id' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.String value) {
    this.transaction_id = value;
  }

  /**
   * Creates a new SubmissionRecord RecordBuilder.
   * @return A new SubmissionRecord RecordBuilder
   */
  public static uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder newBuilder() {
    return new uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder();
  }

  /**
   * Creates a new SubmissionRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SubmissionRecord RecordBuilder
   */
  public static uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder newBuilder(uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder other) {
    return new uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder(other);
  }

  /**
   * Creates a new SubmissionRecord RecordBuilder by copying an existing SubmissionRecord instance.
   * @param other The existing instance to copy.
   * @return A new SubmissionRecord RecordBuilder
   */
  public static uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder newBuilder(uk.gov.companieshouse.filing.processed.SubmissionRecord other) {
    return new uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder(other);
  }

  /**
   * RecordBuilder for SubmissionRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SubmissionRecord>
    implements org.apache.avro.data.RecordBuilder<SubmissionRecord> {

    private java.lang.String transaction_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[0].schema(), other.transaction_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SubmissionRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(uk.gov.companieshouse.filing.processed.SubmissionRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[0].schema(), other.transaction_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'transaction_id' field.
      * @return The value.
      */
    public java.lang.String getTransactionId() {
      return transaction_id;
    }

    /**
      * Sets the value of the 'transaction_id' field.
      * @param value The value of 'transaction_id'.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder setTransactionId(java.lang.String value) {
      validate(fields()[0], value);
      this.transaction_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_id' field has been set.
      * @return True if the 'transaction_id' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transaction_id' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.processed.SubmissionRecord.Builder clearTransactionId() {
      transaction_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public SubmissionRecord build() {
      try {
        SubmissionRecord record = new SubmissionRecord();
        record.transaction_id = fieldSetFlags()[0] ? this.transaction_id : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
