/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package uk.gov.companieshouse.filing.received;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SubmissionRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3349629909390652041L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SubmissionRecord\",\"namespace\":\"uk.gov.companieshouse.filing.received\",\"fields\":[{\"name\":\"company_number\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"company_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"received_at\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"transaction_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String company_number;
  @Deprecated public java.lang.String company_name;
  @Deprecated public java.lang.String received_at;
  @Deprecated public java.lang.String transaction_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SubmissionRecord() {}

  /**
   * All-args constructor.
   * @param company_number The new value for company_number
   * @param company_name The new value for company_name
   * @param received_at The new value for received_at
   * @param transaction_id The new value for transaction_id
   */
  public SubmissionRecord(java.lang.String company_number, java.lang.String company_name, java.lang.String received_at, java.lang.String transaction_id) {
    this.company_number = company_number;
    this.company_name = company_name;
    this.received_at = received_at;
    this.transaction_id = transaction_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return company_number;
    case 1: return company_name;
    case 2: return received_at;
    case 3: return transaction_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: company_number = (java.lang.String)value$; break;
    case 1: company_name = (java.lang.String)value$; break;
    case 2: received_at = (java.lang.String)value$; break;
    case 3: transaction_id = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'company_number' field.
   * @return The value of the 'company_number' field.
   */
  public java.lang.String getCompanyNumber() {
    return company_number;
  }

  /**
   * Sets the value of the 'company_number' field.
   * @param value the value to set.
   */
  public void setCompanyNumber(java.lang.String value) {
    this.company_number = value;
  }

  /**
   * Gets the value of the 'company_name' field.
   * @return The value of the 'company_name' field.
   */
  public java.lang.String getCompanyName() {
    return company_name;
  }

  /**
   * Sets the value of the 'company_name' field.
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.String value) {
    this.company_name = value;
  }

  /**
   * Gets the value of the 'received_at' field.
   * @return The value of the 'received_at' field.
   */
  public java.lang.String getReceivedAt() {
    return received_at;
  }

  /**
   * Sets the value of the 'received_at' field.
   * @param value the value to set.
   */
  public void setReceivedAt(java.lang.String value) {
    this.received_at = value;
  }

  /**
   * Gets the value of the 'transaction_id' field.
   * @return The value of the 'transaction_id' field.
   */
  public java.lang.String getTransactionId() {
    return transaction_id;
  }

  /**
   * Sets the value of the 'transaction_id' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.String value) {
    this.transaction_id = value;
  }

  /**
   * Creates a new SubmissionRecord RecordBuilder.
   * @return A new SubmissionRecord RecordBuilder
   */
  public static uk.gov.companieshouse.filing.received.SubmissionRecord.Builder newBuilder() {
    return new uk.gov.companieshouse.filing.received.SubmissionRecord.Builder();
  }

  /**
   * Creates a new SubmissionRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SubmissionRecord RecordBuilder
   */
  public static uk.gov.companieshouse.filing.received.SubmissionRecord.Builder newBuilder(uk.gov.companieshouse.filing.received.SubmissionRecord.Builder other) {
    return new uk.gov.companieshouse.filing.received.SubmissionRecord.Builder(other);
  }

  /**
   * Creates a new SubmissionRecord RecordBuilder by copying an existing SubmissionRecord instance.
   * @param other The existing instance to copy.
   * @return A new SubmissionRecord RecordBuilder
   */
  public static uk.gov.companieshouse.filing.received.SubmissionRecord.Builder newBuilder(uk.gov.companieshouse.filing.received.SubmissionRecord other) {
    return new uk.gov.companieshouse.filing.received.SubmissionRecord.Builder(other);
  }

  /**
   * RecordBuilder for SubmissionRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SubmissionRecord>
    implements org.apache.avro.data.RecordBuilder<SubmissionRecord> {

    private java.lang.String company_number;
    private java.lang.String company_name;
    private java.lang.String received_at;
    private java.lang.String transaction_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(uk.gov.companieshouse.filing.received.SubmissionRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.company_number)) {
        this.company_number = data().deepCopy(fields()[0].schema(), other.company_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.company_name)) {
        this.company_name = data().deepCopy(fields()[1].schema(), other.company_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.received_at)) {
        this.received_at = data().deepCopy(fields()[2].schema(), other.received_at);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[3].schema(), other.transaction_id);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SubmissionRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(uk.gov.companieshouse.filing.received.SubmissionRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.company_number)) {
        this.company_number = data().deepCopy(fields()[0].schema(), other.company_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.company_name)) {
        this.company_name = data().deepCopy(fields()[1].schema(), other.company_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.received_at)) {
        this.received_at = data().deepCopy(fields()[2].schema(), other.received_at);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[3].schema(), other.transaction_id);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'company_number' field.
      * @return The value.
      */
    public java.lang.String getCompanyNumber() {
      return company_number;
    }

    /**
      * Sets the value of the 'company_number' field.
      * @param value The value of 'company_number'.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.received.SubmissionRecord.Builder setCompanyNumber(java.lang.String value) {
      validate(fields()[0], value);
      this.company_number = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'company_number' field has been set.
      * @return True if the 'company_number' field has been set, false otherwise.
      */
    public boolean hasCompanyNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'company_number' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.received.SubmissionRecord.Builder clearCompanyNumber() {
      company_number = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'company_name' field.
      * @return The value.
      */
    public java.lang.String getCompanyName() {
      return company_name;
    }

    /**
      * Sets the value of the 'company_name' field.
      * @param value The value of 'company_name'.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.received.SubmissionRecord.Builder setCompanyName(java.lang.String value) {
      validate(fields()[1], value);
      this.company_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'company_name' field has been set.
      * @return True if the 'company_name' field has been set, false otherwise.
      */
    public boolean hasCompanyName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'company_name' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.received.SubmissionRecord.Builder clearCompanyName() {
      company_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'received_at' field.
      * @return The value.
      */
    public java.lang.String getReceivedAt() {
      return received_at;
    }

    /**
      * Sets the value of the 'received_at' field.
      * @param value The value of 'received_at'.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.received.SubmissionRecord.Builder setReceivedAt(java.lang.String value) {
      validate(fields()[2], value);
      this.received_at = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'received_at' field has been set.
      * @return True if the 'received_at' field has been set, false otherwise.
      */
    public boolean hasReceivedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'received_at' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.received.SubmissionRecord.Builder clearReceivedAt() {
      received_at = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'transaction_id' field.
      * @return The value.
      */
    public java.lang.String getTransactionId() {
      return transaction_id;
    }

    /**
      * Sets the value of the 'transaction_id' field.
      * @param value The value of 'transaction_id'.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.received.SubmissionRecord.Builder setTransactionId(java.lang.String value) {
      validate(fields()[3], value);
      this.transaction_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_id' field has been set.
      * @return True if the 'transaction_id' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'transaction_id' field.
      * @return This builder.
      */
    public uk.gov.companieshouse.filing.received.SubmissionRecord.Builder clearTransactionId() {
      transaction_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public SubmissionRecord build() {
      try {
        SubmissionRecord record = new SubmissionRecord();
        record.company_number = fieldSetFlags()[0] ? this.company_number : (java.lang.String) defaultValue(fields()[0]);
        record.company_name = fieldSetFlags()[1] ? this.company_name : (java.lang.String) defaultValue(fields()[1]);
        record.received_at = fieldSetFlags()[2] ? this.received_at : (java.lang.String) defaultValue(fields()[2]);
        record.transaction_id = fieldSetFlags()[3] ? this.transaction_id : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
